/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package factura_y_presupuesto.MostrarDetalle;

/**
 *
 * @author garca
 */
public class MostrarDetalle extends javax.swing.JFrame {

    /**
     * Creates new form MostrarDetalle
     */
    public MostrarDetalle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel_codigodebarra = new javax.swing.JLabel();
        jLabel_preciounitario = new javax.swing.JLabel();
        jLabel_cantidad = new javax.swing.JLabel();
        jLabel_subtotal = new javax.swing.JLabel();
        jLabel_nombreproducto = new javax.swing.JLabel();
        jLabel_precio = new javax.swing.JLabel();
        jLabel_unidaddemedida = new javax.swing.JLabel();
        jLabel_descripcion = new javax.swing.JLabel();
        jLabel_nombre = new javax.swing.JLabel();
        jLabel_Precio = new javax.swing.JLabel();
        jLabel_preciounitario1 = new javax.swing.JLabel();
        jLabel_cantidad1 = new javax.swing.JLabel();
        jLabel_subtotal1 = new javax.swing.JLabel();
        jLabel_unidad = new javax.swing.JLabel();
        jLabel_descripcion1 = new javax.swing.JLabel();
        jLabel_codigodebarra1 = new javax.swing.JLabel();
        jButton_volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Detalle");

        jLabel_codigodebarra.setText("Codigo de barra");

        jLabel_preciounitario.setText("Precio unitario");

        jLabel_cantidad.setText("Cantidad");

        jLabel_subtotal.setText("Subtotal");

        jLabel_nombreproducto.setText("Nombre producto");

        jLabel_precio.setText("Precio");

        jLabel_unidaddemedida.setText("Unidad de medida");

        jLabel_descripcion.setText("Descripcion");

        jLabel_nombre.setText("nombre");

        jLabel_Precio.setText("precio");

        jLabel_preciounitario1.setText("Precio unitario");

        jLabel_cantidad1.setText("Cantidad");

        jLabel_subtotal1.setText("Subtotal");

        jLabel_unidad.setText("Unidad de medida");

        jLabel_descripcion1.setText("Descripcion");

        jLabel_codigodebarra1.setText("Codigo de barra");

        jButton_volver.setText("Volver");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton_volver)
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_nombreproducto)
                            .addComponent(jLabel_precio)
                            .addComponent(jLabel_codigodebarra)
                            .addComponent(jLabel_preciounitario)
                            .addComponent(jLabel_cantidad)
                            .addComponent(jLabel_subtotal)
                            .addComponent(jLabel_unidaddemedida)
                            .addComponent(jLabel_descripcion))
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_codigodebarra1)
                            .addComponent(jLabel_preciounitario1)
                            .addComponent(jLabel_cantidad1)
                            .addComponent(jLabel_subtotal1)
                            .addComponent(jLabel_unidad)
                            .addComponent(jLabel_descripcion1)
                            .addComponent(jLabel_Precio)
                            .addComponent(jLabel_nombre)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel1)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_nombreproducto)
                    .addComponent(jLabel_nombre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_precio)
                    .addComponent(jLabel_Precio))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_unidaddemedida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_descripcion)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel_cantidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_codigodebarra)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_preciounitario)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_subtotal))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_unidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_descripcion1)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel_cantidad1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_codigodebarra1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_preciounitario1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_subtotal1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jButton_volver)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarDetalle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Precio;
    private javax.swing.JLabel jLabel_cantidad;
    private javax.swing.JLabel jLabel_cantidad1;
    private javax.swing.JLabel jLabel_codigodebarra;
    private javax.swing.JLabel jLabel_codigodebarra1;
    private javax.swing.JLabel jLabel_descripcion;
    private javax.swing.JLabel jLabel_descripcion1;
    private javax.swing.JLabel jLabel_nombre;
    private javax.swing.JLabel jLabel_nombreproducto;
    private javax.swing.JLabel jLabel_precio;
    private javax.swing.JLabel jLabel_preciounitario;
    private javax.swing.JLabel jLabel_preciounitario1;
    private javax.swing.JLabel jLabel_subtotal;
    private javax.swing.JLabel jLabel_subtotal1;
    private javax.swing.JLabel jLabel_unidad;
    private javax.swing.JLabel jLabel_unidaddemedida;
    // End of variables declaration//GEN-END:variables
}
